import os
from .development import (
    SQLALCHEMY_DATABASE_URI,
    SQLALCHEMY_TRACK_MODIFICATIONS,
    REDIS_URL,
)

# celery
BROKER_URL = os.environ.get("BROKER_URL", "redis://127.0.0.1:6379/2")
BACKEND_URL = os.environ.get("BACKEND_URL", "redis://127.0.0.1:6379/3")
REDIS_URL = os.environ.get("REDIS_URL", REDIS_URL)
SQLALCHEMY_DATABASE_URI = os.environ.get(
    "SQLALCHEMY_DATABASE_URI", SQLALCHEMY_DATABASE_URI
)
SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get(
    "SQLALCHEMY_TRACK_MODIFICATIONS", SQLALCHEMY_TRACK_MODIFICATIONS
)
